### ISSUE TITLE
Documentation & Code comments

### ISSUE THREAD

**Issue by c0D3M** [kmyk/topcoder-marathon-match-repository-template#1]
This template is very useful, however some more comments will make it even more better.

- comment ```xorshift_128``` class and why it is better that existing library function.
- how boltzmann constant is defined, is it like trial and error? , One should start with 0.1 ..0.2 and so and see which value gives a good score?
- a comment on lambda function would be useful.
- a comment on ```get_delta```.
- How to use png and GifWrite ? Is the output of a.out with visualizer fed to these program?.

**Comment by kmyk** [comment]
Thank you for suggestions!
I've updated the contents based on your suggestions.

However, I've moved the contents of this repo to an [article](https://wiki.kimiyuki.net/%E3%83%9E%E3%83%A9%E3%82%BD%E3%83%B3%E3%83%9E%E3%83%83%E3%83%81/%E3%81%9D%E3%81%AE%E4%BB%96/%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88) on my private wiki. Please check this. The reason of this moving is that wiki is easier to edit than GitHub and makes clear that this is a template mainly for myself.

---

> comment xorshift_128 class and why it is better that existing library function.

I added a comment.

> how boltzmann constant is defined, is it like trial and error? , One should start with 0.1 ..0.2 and so and see which value gives a good score?

This is a good question but I don't write this to the template, since this is the problem of SA, not the template.

> a comment on lambda function would be useful.

This is just a choice of implementation. I don't think this is so important to write.

> a comment on get_delta.

This is also a problem about SA, not the template.

> How to use png and GifWrite ? Is the output of a.out with visualizer fed to these program?

I'm sorry that I don't remember it now.  I'll write this the next time when I need to use it. [Here](https://github.com/kmyk/topcoder-marathon-match-100-same-color-pairs/commit/b6f5e14de5b9b16715224b1370c911d420c28af2) is a commit which I embeded `GifWriter.java` to a visualizer, but the same time I said that I should use `javax.imageio.ImageWriter` directly because the compiler fails due to Japanese characters in the file `GifWriter.java`.
